import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'
import { getUserProfile } from '@/lib/supabase/queries'

// GET /api/support/tickets — list tickets for current practice
export async function GET() {
  const profile = await getUserProfile()
  if (!profile?.practice_id) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  const supabase = createClient()
  const { data, error } = await supabase
    .from('support_tickets')
    .select('id, ticket_number, category, subject, status, priority, created_at, updated_at')
    .eq('practice_id', profile.practice_id)
    .order('updated_at', { ascending: false })

  if (error) return NextResponse.json({ error: error.message }, { status: 500 })
  return NextResponse.json(data)
}

// POST /api/support/tickets — create ticket + first message
export async function POST(request: NextRequest) {
  const profile = await getUserProfile()
  if (!profile?.practice_id) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  const { category, subject, message } = await request.json()

  if (!category || !subject || !message) {
    return NextResponse.json({ error: 'Missing required fields: category, subject, message' }, { status: 400 })
  }

  const supabase = createClient()

  // ticket_number is auto-generated by next_ticket_number() DB default
  const { data: ticket, error: ticketError } = await supabase
    .from('support_tickets')
    .insert({
      practice_id: profile.practice_id,
      created_by:  profile.id,
      category,
      subject,
    })
    .select('id, ticket_number')
    .single()

  if (ticketError) return NextResponse.json({ error: ticketError.message }, { status: 500 })

  // Insert first message
  await supabase.from('support_ticket_messages').insert({
    ticket_id:   ticket.id,
    sender_id:   profile.id,
    sender_role: 'practice_user',
    body:        message,
  })

  return NextResponse.json({ id: ticket.id, ticket_number: ticket.ticket_number }, { status: 201 })
}
